# Generated by Django 3.1 on 2025-06-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20250617_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='previous_evolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolution', to='pokemon_entities.pokemonentity', verbose_name='Эволюция'),
        ),
    ]
